name = "web-vitals"
type = "javascript"

usage_model = 'unbound'

account_id = '85a31fecb794eb22c6b5cd6f2ee073b8'
workers_dev = true
route = ''
zone_id = ''

[build]
command = "pnpm run build"
watch_dir = "src"

[build.upload]
format = "modules"
dir = "dist"
main = "./worker.mjs"
