name = "web-vitals-api"
type = "javascript"

usage_model = 'unbound'

account_id = '85a31fecb794eb22c6b5cd6f2ee073b8'
workers_dev = false
routes = ['https://vitals.htm.io/*']
zone_id = '2b88e3a435ca067ea04e8acd42fc08b4'

kv_namespaces = [
    { binding = "METRICS", id = "b23b569d751a4096bd1ab5bb625a3727", preview_id = "b23b569d751a4096bd1ab5bb625a3727" }
]

[build]
command = "pnpm run build"
watch_dir = "src"

[dev]
port = 8081

[build.upload]
format = "service-worker"
