name = "web-vitals"
type = "javascript"

usage_model = 'bundled'

account_id = '85a31fecb794eb22c6b5cd6f2ee073b8'
workers_dev = false
routes = ['htm.io/*']
zone_id = '2b88e3a435ca067ea04e8acd42fc08b4'

kv_namespaces = [
    { binding = "METRICS", id = "b23b569d751a4096bd1ab5bb625a3727", preview_id = "b23b569d751a4096bd1ab5bb625a3727" }
]

[build]
command = "pnpm run build"
watch_dir = "src"

[dev]
port = 8081

#[site]
#bucket = "./public"
#entry-point = "."

[build.upload]
format = "service-worker"
#dir = "dist"
#main = "./worker.mjs"

#[durable_objects]
#bindings = [{name = "METRICS", class_name = "Metrics"}]
